version: "3"

services:
  mongo:
    container_name: mongo
    image: bitnami/mongodb:latest
    restart: always
    volumes:
      - "${MONGODB_PATH:-./mongodb}:/data/db"
    networks:
      - gpt_internal_network

  longevitygpt_telegram_bot:
    container_name: longevitygpt_telegram_bot
    command: python3 bot/bot.py
    restart: always
    build:
      context: "."
      dockerfile: Dockerfile
    depends_on:
      - mongo
    networks:
      - gpt_internal_network
    environment:   
      - HOST_API_URL=http://host.docker.internal:8008

  mongo_express:
    container_name: mongo-express
    image: mongo-express:latest
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=${MONGODB_PORT:-27017}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=chatgpt_telegram_bot
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USERNAME:-username}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD:-password}
    depends_on:
      - mongo
    networks:
      - gpt_internal_network

networks:
  gpt_internal_network:
